
client_id = "5045aa8f0d16fbd8e6ee66207cb39a8e"
name = "Wagtail-CMS"
application_url = "https://wagtail-dev.aadigitalbusiness.com/shopify-admin"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_content,read_online_store_pages,write_content,write_online_store_pages,read_products,write_products,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://wagtail-dev.aadigitalbusiness.com/auth/callback" ]
