# Generated by Django 5.2.15 on 2026-06-14 05:10

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "shopify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shopify GID, e.g. gid://shopify/Blog/12345678",
                        max_length=255,
                    ),
                ),
                ("handle", models.SlugField(blank=True, max_length=255)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment_policy",
                    models.CharField(
                        choices=[
                            ("AUTO_PUBLISHED", "Auto Published (visible immediately)"),
                            ("CLOSED", "Closed (no comments)"),
                            ("MODERATED", "Moderated (staff approval required)"),
                        ],
                        default="CLOSED",
                        help_text="Maps to Shopify Blog commentPolicy.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CollectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "shopify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shopify GID, e.g. gid://shopify/Collection/12345678",
                        max_length=255,
                    ),
                ),
                ("handle", models.SlugField(blank=True, max_length=255)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sort_order",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALPHA_ASC", "Alphabetically A–Z"),
                            ("ALPHA_DESC", "Alphabetically Z–A"),
                            ("BEST_SELLING", "Best Selling"),
                            ("CREATED", "Date Created (Oldest First)"),
                            ("CREATED_DESC", "Date Created (Newest First)"),
                            ("MANUAL", "Manually"),
                            ("PRICE_ASC", "Price Ascending"),
                            ("PRICE_DESC", "Price Descending"),
                        ],
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 4),
                            ("image", 8),
                            ("callout", 11),
                            ("html", 12),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "required": True,
                                },
                            ),
                            4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alt text overrides the image title for accessibility.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("alt_text", 6), ("caption", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("tip", "Tip"),
                                        ("note", "Note"),
                                    ]
                                },
                            ),
                            10: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("callout_type", 9), ("text", 10)]],
                                {},
                            ),
                            12: ("shopify_content.blocks.content.HtmlBlock", (), {}),
                        },
                        help_text="Collection description. Rendered to HTML for Shopify descriptionHtml.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Page",
                "verbose_name_plural": "Collection Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "shopify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shopify GID, e.g. gid://shopify/Product/12345678",
                        max_length=255,
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        blank=True,
                        help_text="Shopify URL handle. Populated automatically on inbound import.",
                        max_length=255,
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When unchecked, publishing will NOT sync to Shopify.",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("product_type", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("DRAFT", "Draft"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 4),
                            ("image", 8),
                            ("video", 10),
                            ("feature", 14),
                            ("callout", 17),
                            ("html", 18),
                            ("metafield", 22),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "required": True,
                                },
                            ),
                            4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alt text overrides the image title for accessibility.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("alt_text", 6), ("caption", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "YouTube or Vimeo video URL.",
                                    "required": True,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("url", 9), ("caption", 7)]],
                                {},
                            ),
                            11: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Optional SVG or PNG icon for this feature.",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 11), ("title", 12), ("description", 13)]],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("tip", "Tip"),
                                        ("note", "Note"),
                                    ]
                                },
                            ),
                            16: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [[("callout_type", 15), ("text", 16)]],
                                {},
                            ),
                            18: ("shopify_content.blocks.content.HtmlBlock", (), {}),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "custom",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 64, "required": True},
                            ),
                            21: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("single_line_text_field", "Single Line Text"),
                                        ("multi_line_text_field", "Multi Line Text"),
                                        ("json", "JSON"),
                                        ("number_integer", "Integer"),
                                        ("number_decimal", "Decimal"),
                                        ("boolean", "Boolean"),
                                        ("color", "Color"),
                                        ("date", "Date"),
                                        ("date_time", "Date & Time"),
                                        ("url", "URL"),
                                        ("rich_text_field", "Rich Text (HTML)"),
                                        ("file_reference", "File Reference"),
                                        ("page_reference", "Page Reference"),
                                        ("product_reference", "Product Reference"),
                                        (
                                            "collection_reference",
                                            "Collection Reference",
                                        ),
                                        ("variant_reference", "Variant Reference"),
                                        (
                                            "metaobject_reference",
                                            "Metaobject Reference",
                                        ),
                                    ]
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("namespace", 19),
                                        ("key", 20),
                                        ("type", 21),
                                        ("value", 13),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Product description. Rendered to HTML for Shopify descriptionHtml.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Page",
                "verbose_name_plural": "Product Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ShopifyRootPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Root",
                "verbose_name_plural": "Shopify Roots",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "shopify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shopify GID, e.g. gid://shopify/Article/12345678",
                        max_length=255,
                    ),
                ),
                ("handle", models.SlugField(blank=True, max_length=255)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author full name. Maps to Shopify AuthorInput.name.",
                        max_length=255,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Maps to Shopify publishedAt. Auto-set on first publish if blank.",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short summary (HTML allowed). Maps to Shopify article summary field.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 4),
                            ("image", 8),
                            ("video", 10),
                            ("callout", 13),
                            ("html", 14),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")]},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "required": True,
                                },
                            ),
                            4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alt text overrides the image title for accessibility.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("alt_text", 6), ("caption", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "YouTube or Vimeo video URL.",
                                    "required": True,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("url", 9), ("caption", 7)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("tip", "Tip"),
                                        ("note", "Note"),
                                    ]
                                },
                            ),
                            12: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("callout_type", 11), ("text", 12)]],
                                {},
                            ),
                            14: ("shopify_content.blocks.content.HtmlBlock", (), {}),
                        },
                        help_text="Article body content. Rendered to HTML for Shopify body field.",
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Maps to Shopify Article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePageMetafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(default="custom", max_length=255)),
                ("key", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        default="single_line_text_field",
                        help_text="Shopify metafield type, e.g. single_line_text_field, json, url",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="shopify_content.articlepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticlePageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="shopify_content.articlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="articlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="shopify_content.ArticlePageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="CollectionPageMetafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(default="custom", max_length=255)),
                ("key", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        default="single_line_text_field",
                        help_text="Shopify metafield type, e.g. single_line_text_field, json, url",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="shopify_content.collectionpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductPageMetafield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(default="custom", max_length=255)),
                ("key", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        default="single_line_text_field",
                        help_text="Shopify metafield type, e.g. single_line_text_field, json, url",
                        max_length=100,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metafields",
                        to="shopify_content.productpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="shopify_content.productpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="shopify_content.ProductPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
