# Generated by Django 5.2.15 on 2026-06-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Blog description (HTML allowed). Synced as metafield descriptors.description.",
            ),
        ),
    ]
