# Generated by Django 5.2.15 on 2026-06-17 01:26

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify_content", "0003_add_faq_items"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "shopify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shopify metaobject GID (populated after first upsert)",
                        max_length=255,
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        blank=True,
                        help_text="Shopify metaobject handle (defaults to page slug)",
                        max_length=255,
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "subtitulo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítulo"
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Intro"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="State / Province"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "titulo_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Título 2"
                    ),
                ),
                (
                    "subtitulo_h2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítulo H2"
                    ),
                ),
                (
                    "content_2",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Content 2"),
                ),
                (
                    "titulo_3",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Título 3"
                    ),
                ),
                (
                    "subtitulo_3",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtítulo 3"
                    ),
                ),
                (
                    "content_3",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Content 3"),
                ),
                (
                    "brand_section_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Brand Section Title"
                    ),
                ),
                (
                    "brand_section_subtitle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Brand Section Subtitle",
                    ),
                ),
                (
                    "brand_section_content",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Brand Section Content"
                    ),
                ),
                (
                    "map_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Map Title"
                    ),
                ),
                (
                    "map_content",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Map Content"
                    ),
                ),
                (
                    "after_page_content",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="After Page Content"
                    ),
                ),
                (
                    "shopify_locale",
                    models.CharField(
                        blank=True,
                        help_text='Shopify locale code pushed to the locale field (e.g. "es", "en-CA").',
                        max_length=20,
                        verbose_name="Shopify Locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Page",
                "verbose_name_plural": "Location Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LocationPageFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="shopify_content.locationpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
