# Generated by Django 6.0.6 on 2026-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_content', '0004_add_location_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='shopify_locale',
            field=models.CharField(blank=True, choices=[('en-US', 'English (United States)'), ('es-US', 'Spanish (United States)'), ('en-CA', 'English (Canada)'), ('fr-CA', 'French (Canada)')], help_text='Shopify locale code pushed to the locale field (e.g. "es", "en-CA").', max_length=20, verbose_name='Shopify Locale'),
        ),
    ]
