# Generated by Django 6.0.6 on 2026-06-17 14:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_content', '0005_alter_locationpage_shopify_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Absolute Shopify article image URL for img src.', max_length=2048),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='shopify_featured_image_id',
            field=models.CharField(blank=True, help_text='Shopify MediaImage GID for the article featured image.', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Absolute Shopify collection image URL for img src.', max_length=2048),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='shopify_image_id',
            field=models.CharField(blank=True, help_text='Shopify MediaImage GID for the collection image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Manual Wagtail image upload. Pull from Shopify uses featured_image_url instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='ProductPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(blank=True, help_text='Shopify MediaImage GID.', max_length=255)),
                ('url', models.URLField(help_text='Absolute CDN URL for use in img src.', max_length=2048)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_images', to='shopify_content.productpage')),
            ],
            options={
                'verbose_name': 'Shopify product image',
                'verbose_name_plural': 'Shopify product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
