# Generated by Django 6.0.6 on 2026-06-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_content', '0006_product_image_urls'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifySyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inbound', 'Inbound (Shopify → Wagtail)'), ('outbound', 'Outbound (Wagtail → Shopify)')], max_length=16)),
                ('resource', models.CharField(blank=True, help_text='products, collections, blogs, or all (inbound only)', max_length=32)),
                ('new_only', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_sync_runs', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Shopify sync run',
                'verbose_name_plural': 'Shopify sync runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
