# Generated by Django 6.0.6 on 2026-06-28 07:19

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_content', '0007_shopify_sync_run'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTermPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('shopify_id', models.CharField(blank=True, db_index=True, help_text='Shopify metaobject GID (populated after first upsert)', max_length=255)),
                ('handle', models.SlugField(blank=True, help_text='Shopify metaobject handle (defaults to slugified term)', max_length=255)),
                ('sync_enabled', models.BooleanField(db_default=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('definition', wagtail.fields.RichTextField(blank=True)),
                ('locale_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Locale pushed to the Shopify locale field.', max_length=10)),
                ('related_links', models.JSONField(blank=True, default=list)),
                ('external_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'verbose_name_plural': 'Glossary Terms',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 4), ('image', 8), ('video', 10), ('callout', 13), ('html', 14), ('product_banner', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr'], 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text overrides the image title for accessibility.', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo video URL.', 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('url', 9), ('caption', 7)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('tip', 'Tip'), ('note', 'Note')]}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('callout_type', 11), ('text', 12)]], {}), 14: ('shopify_content.blocks.content.HtmlBlock', (), {}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select the product to display in banner.', 'page_type': ['shopify_content.ProductPage'], 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('product', 15)]], {})}, help_text='Article body content. Rendered to HTML for Shopify body field.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True, help_text='When unchecked, publishing will NOT sync to Shopify.'),
        ),
        migrations.CreateModel(
            name='ArticleRelatedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_related_pages', to='shopify_content.articlepage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Related page',
                'verbose_name_plural': 'Related pages',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
