# Generated by Django 6.0.8 on 2026-09-14 00:56

import django.db.models.deletion
import modelcluster.fields
import shopify_content.content_store.domain
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_content', '0009_shopifyrootpage_operational_fields'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedCommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(db_index=True, max_length=64)),
                ('command_name', models.CharField(max_length=128)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Embedded command run',
                'verbose_name_plural': 'Embedded command runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Wagtail locale codes (en-US, es-US, en-CA, fr-CA) where this content is published for the storefront.'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Wagtail locale codes (en-US, es-US, en-CA, fr-CA) where this content is published for the storefront.'),
        ),
        migrations.AddField(
            model_name='collectionpage',
            name='theme_config',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='Theme storefront overrides pushed as Shopify metafields on sync. Schema: {"metafields": [{"namespace": "custom", "key": "...", "type": "json", "value": "..."}]}'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='theme_config',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='Theme storefront overrides pushed as Shopify metafields on sync. Schema: {"metafields": [{"namespace": "custom", "key": "...", "type": "json", "value": "..."}]}'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 4), ('image', 8), ('video', 10), ('callout', 13), ('html', 14), ('product_banner', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr'], 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('text', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text overrides the image title for accessibility.', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('alt_text', 6), ('caption', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo video URL.', 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('url', 9), ('caption', 7)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info'), ('warning', 'Warning'), ('tip', 'Tip'), ('note', 'Note')]}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('callout_type', 11), ('text', 12)]], {}), 14: ('shopify_content.blocks.content.HtmlBlock', (), {}), 15: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select the product to display in banner.', 'page_type': ['shopify_content.ProductPage'], 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('product', 15)]], {})}, help_text='Article body content. Rendered to HTML for Shopify body field.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='handle',
            field=models.SlugField(blank=True, help_text='Shopify metaobject handle (auto-derived as <locale>-<city>[-<state>])', max_length=255),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='sync_enabled',
            field=models.BooleanField(db_default=True, default=True, help_text='When unchecked, publishing will NOT sync to Shopify.'),
        ),
        migrations.AlterField(
            model_name='shopifyrootpage',
            name='export_config',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='Type-specific export payload pushed to Shopify metaobject field config. Example for slug=glossary: glossary_index.page_gid pointing to Shopify Page handle glossary.'),
        ),
        migrations.CreateModel(
            name='ArticleRelatedArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='shopify_content.articlepage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Related articles',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedCollectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_collections', to='shopify_content.articlepage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Related collections',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedGlossaryTermLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_glossary_terms', to='shopify_content.articlepage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Related glossary terms',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleRelatedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shopify_content.articlepage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Related products',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionRelatedArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='shopify_content.collectionpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Related articles',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionRelatedCollectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_collections', to='shopify_content.collectionpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Related collections',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionRelatedGlossaryTermLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_glossary_terms', to='shopify_content.collectionpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Related glossary terms',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionRelatedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shopify_content.collectionpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Related products',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('shopify_id', models.CharField(blank=True, db_index=True, help_text='Shopify metaobject GID (populated after first upsert)', max_length=255)),
                ('handle', models.SlugField(blank=True, help_text='Shopify metaobject handle (defaults to slugified term)', max_length=255)),
                ('sync_enabled', models.BooleanField(db_default=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('definition', wagtail.fields.RichTextField(blank=True)),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text mirror from Shopify (or used on Wagtail upload).', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='Absolute Shopify CDN URL (mirror). Populated on pull/refresh; used by the glossary index. Shopify owns media.', max_length=500)),
                ('shopify_image_id', models.CharField(blank=True, help_text='Shopify File/MediaImage GID (mirror of metaobject image). Shopify is source of truth; outbound only writes this field after an explicit Wagtail upload.', max_length=255)),
                ('locale_code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', help_text='Locale pushed to the Shopify locale field.', max_length=10)),
                ('related_links', models.JSONField(blank=True, db_default=[], default=list)),
                ('external_links', models.JSONField(blank=True, db_default=[], default=list)),
                ('synonyms', models.JSONField(blank=True, db_default=[], default=list, help_text='Sinónimos / siglas / variantes. Lista de strings → Shopify list.single_line_text_field')),
                ('same_as', models.JSONField(blank=True, db_default=[], default=list, help_text='URLs de entidad canónica externa (Wikipedia/Wikidata). Lista de URLs → Shopify list.url')),
                ('image', models.ForeignKey(blank=True, help_text='Optional Wagtail upload to create/replace the Shopify File when shopify_image_id is empty. Shopify owns media; clear shopify_image_id to force a new upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Glossary Term',
                'verbose_name_plural': 'Glossary Terms',
            },
            bases=(shopify_content.content_store.domain.EditorialMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='GlossaryTermRelatedArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='shopify_content.glossarytermpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Related articles',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermRelatedCollectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_collections', to='shopify_content.glossarytermpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Related collections',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermRelatedGlossaryTermLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_glossary_terms', to='shopify_content.glossarytermpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Related glossary terms',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GlossaryTermRelatedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shopify_content.glossarytermpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Related products',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('shopify_id', models.CharField(blank=True, db_index=True, help_text='Shopify metaobject GID (populated after first upsert)', max_length=255)),
                ('handle', models.SlugField(blank=True, help_text='Shopify metaobject handle (auto-derived as home-<locale>)', max_length=255)),
                ('sync_enabled', models.BooleanField(db_default=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_locale', models.CharField(blank=True, choices=[('en-US', 'English (United States)'), ('es-US', 'Spanish (United States)'), ('en-CA', 'English (Canada)'), ('fr-CA', 'French (Canada)')], help_text='Locale code pushed to Shopify (e.g. en-US). Blank uses Wagtail locale.', max_length=20, verbose_name='Shopify Locale')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=60, verbose_name='Hero eyebrow')),
                ('hero_heading', models.CharField(max_length=255, verbose_name='Hero heading')),
                ('hero_subheading', models.CharField(blank=True, max_length=500, verbose_name='Hero subheading')),
                ('hero_body', wagtail.fields.RichTextField(blank=True, verbose_name='Hero body')),
                ('hero_primary_cta_label', models.CharField(blank=True, max_length=255, verbose_name='Primary CTA label')),
                ('hero_primary_cta_url', models.CharField(blank=True, help_text='Storefront path (e.g. /collections/all) or absolute https URL.', max_length=500, verbose_name='Primary CTA URL')),
                ('hero_secondary_cta_label', models.CharField(blank=True, max_length=255, verbose_name='Secondary CTA label')),
                ('hero_secondary_cta_url', models.CharField(blank=True, help_text='Storefront path (e.g. /collections/all) or absolute https URL.', max_length=500, verbose_name='Secondary CTA URL')),
                ('hero_image_url', models.URLField(blank=True, help_text='Absolute hero image URL pushed to Shopify. Auto-filled from hero_image on sync.', max_length=500)),
                ('body', wagtail.fields.StreamField([('promo_gateway', 10), ('nav_collection_pills', 15), ('trust_bar', 21), ('featured_collections', 27), ('editorial_intro', 30), ('best_sellers', 34), ('shop_by_need', 41), ('educational_hub', 46), ('brand_values', 53), ('market_block', 57), ('faq', 63), ('internal_links', 68), ('seo_schema', 70)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('collection_products', 'Collection products'), ('collection_list', 'Collection list')], 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['shopify_content.CollectionPage'], 'required': False}), 4: ('wagtail.blocks.ListBlock', (3,), {'max_num': 4, 'min_num': 0, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Shop trending', 'max_length': 80, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Storefront path (e.g. /collections/all) or absolute https URL.', 'max_length': 500, 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', '1 column'), ('2', '2 columns')], 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('badge', 1), ('media_source', 2), ('primary_collection', 3), ('category_collections', 4), ('cta_label', 5), ('cta_url', 6), ('column_span', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'max_num': 4, 'min_num': 0}), 10: ('wagtail.blocks.StructBlock', [[('cards', 9)]], {}), 11: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'If items are empty, seed pills from this collection’s related_collections.', 'page_type': ['shopify_content.CollectionPage'], 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['shopify_content.CollectionPage'], 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('collection', 12), ('override_label', 1)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'max_num': 8, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('source_collection', 11), ('items', 14)]], {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('local_shipping', 'Shipping'), ('verified', 'Verified'), ('lock', 'Secure'), ('favorite', 'Inclusive'), ('shield', 'Shield'), ('support_agent', 'Support')], 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('icon', 16), ('title', 17), ('description', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'max_num': 6, 'min_num': 0}), 21: ('wagtail.blocks.StructBlock', [[('items', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('collection', 12), ('override_title', 23), ('override_label', 1)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'max_num': 6, 'min_num': 0}), 27: ('wagtail.blocks.StructBlock', [[('badge', 22), ('title', 23), ('intro', 24), ('items', 26)]], {}), 28: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': False}), 29: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center')], 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('heading', 23), ('body', 28), ('alignment', 29)]], {}), 31: ('wagtail.blocks.IntegerBlock', (), {'default': 8, 'max_value': 12, 'min_value': 4, 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': False}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('contrast', 'Contrast')], 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 23), ('collection', 3), ('product_limit', 31), ('badge', 32), ('background', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 36: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['shopify_content.CollectionPage', 'shopify_content.ProductPage'], 'required': False}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Shop', 'max_length': 40, 'required': False}), 38: ('wagtail.blocks.URLBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('title', 17), ('description', 35), ('target_page', 36), ('cta_label', 37), ('cta_url', 6), ('image_url', 38), ('intent_tag', 22)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'max_num': 8, 'min_num': 0}), 41: ('wagtail.blocks.StructBlock', [[('title', 23), ('cards', 40)]], {}), 42: ('shopify_content.blocks.home.LocaleAwarePageChooserBlock', (), {'page_type': ['shopify_content.ProductPage', 'shopify_content.CollectionPage', 'shopify_content.ArticlePage', 'shopify_content.GlossaryTermPage', 'shopify_content.BlogPage'], 'required': True}), 43: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 44: ('wagtail.blocks.StructBlock', [[('page', 42), ('label', 43), ('description', 35)]], {}), 45: ('wagtail.blocks.ListBlock', (44,), {'max_num': 6, 'min_num': 0}), 46: ('wagtail.blocks.StructBlock', [[('title', 23), ('intro', 24), ('links', 45)]], {}), 47: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 48: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 49: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 50: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')], 'required': False}), 51: ('wagtail.blocks.StructBlock', [[('icon', 22), ('title', 17), ('description', 18)]], {}), 52: ('wagtail.blocks.ListBlock', (51,), {'max_num': 4, 'required': False}), 53: ('wagtail.blocks.StructBlock', [[('eyebrow', 47), ('heading', 23), ('body', 48), ('image', 49), ('image_url', 38), ('media_position', 50), ('values', 52), ('cta_label', 1), ('cta_url', 6)]], {}), 54: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 55: ('wagtail.blocks.ListBlock', (54,), {'max_num': 4, 'required': False}), 56: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('US', 'United States'), ('CA', 'Canada')], 'required': False}), 57: ('wagtail.blocks.StructBlock', [[('heading', 23), ('body', 48), ('highlights', 55), ('cta_label', 1), ('cta_url', 6), ('market_code', 56)]], {}), 58: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently asked questions', 'max_length': 120, 'required': False}), 59: ('wagtail.blocks.CharBlock', (), {'max_length': 500, 'required': True}), 60: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 61: ('wagtail.blocks.StructBlock', [[('question', 59), ('answer', 60)]], {}), 62: ('wagtail.blocks.ListBlock', (61,), {'max_num': 6, 'min_num': 0}), 63: ('wagtail.blocks.StructBlock', [[('heading', 58), ('items', 62)]], {}), 64: ('wagtail.blocks.StructBlock', [[('page', 42), ('label', 1)]], {}), 65: ('wagtail.blocks.ListBlock', (64,), {'max_num': 12, 'min_num': 0}), 66: ('wagtail.blocks.StructBlock', [[('title', 1), ('links', 65)]], {}), 67: ('wagtail.blocks.ListBlock', (66,), {'max_num': 6, 'min_num': 0}), 68: ('wagtail.blocks.StructBlock', [[('heading', 23), ('groups', 67)]], {}), 69: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 70: ('wagtail.blocks.StructBlock', [[('include_faq_schema', 69), ('include_organization', 69)]], {})}, verbose_name='Home sections')),
                ('sections_json', models.JSONField(blank=True, db_default={}, default=dict, help_text='Home sections JSON (version 1, 13 canonical types). Derived from body StreamField on save. See docs/home-page-content-schema.json.')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Optional hero image; URL is pushed to Shopify on sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductRelatedArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to='shopify_content.productpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Related articles',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRelatedCollectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_collections', to='shopify_content.productpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Related collections',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRelatedGlossaryTermLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_glossary_terms', to='shopify_content.productpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Related glossary terms',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRelatedProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_auto', models.BooleanField(db_default=False, default=False, help_text='True when created by semantic auto-generation on publish.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='shopify_content.productpage')),
                ('related_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Related products',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentUrlIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_path', models.CharField(db_index=True, help_text='Storefront path without domain or locale prefix, e.g. /pages/glossary/alpha', max_length=500)),
                ('content_type', models.CharField(db_index=True, help_text='product, collection, blog, article, glossary_term, location, home, index, root', max_length=32)),
                ('handle', models.CharField(blank=True, db_index=True, max_length=255)),
                ('blog_handle', models.CharField(blank=True, help_text='Parent blog handle for article pages only.', max_length=255)),
                ('locale', models.CharField(blank=True, help_text='Wagtail locale code, e.g. en-US', max_length=16)),
                ('locale_prefix', models.CharField(blank=True, help_text='Shopify Markets URL prefix without slashes, e.g. es-us. Empty for canonical.', max_length=16)),
                ('is_canonical', models.BooleanField(default=True, help_text='True when normalized_path has no Markets locale prefix variant.')),
                ('wagtail_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_url_index_entries', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Content URL index entry',
                'verbose_name_plural': 'Content URL index entries',
                'indexes': [models.Index(fields=['content_type', 'handle'], name='content_url_type_handle_idx'), models.Index(fields=['content_type', 'blog_handle', 'handle'], name='content_url_article_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_path', 'locale_prefix'), name='uniq_content_url_index_path_prefix')],
            },
        ),
    ]
