# Generated by Django 6.0.8 on 2026-09-03 05:24

import django_react_ui_editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSpaMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('url_prefix', models.SlugField(help_text="URL prefix without leading/trailing slashes (e.g. 'cms').", max_length=64)),
                ('editor_app', models.SlugField(default='cms', help_text='Frontend editor app key used by VisualEditorAdminMixin.', max_length=64)),
                ('layout', models.JSONField(blank=True, default=django_react_ui_editor.models.default_layout)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS SPA',
                'verbose_name_plural': 'CMS SPAs',
            },
        ),
    ]
