"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env", override=True)

if "test" in sys.argv:
    os.environ.setdefault("NINJA_SKIP_REGISTRY", "true")


SECRET_KEY = os.environ.get('DJANGO_SECRET')

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    'wagtail-dev.aadigitalbusiness.com',
    'cms.aadigitalbusiness.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://localhost:3458',
    'https://127.0.0.1:3458',
    'https://wagtail-dev.aadigitalbusiness.com',
    'https://cms.aadigitalbusiness.com',
]

_shopify_app_url = os.environ.get('SHOPIFY_APP_URL', '').rstrip('/')
_shopify_app_domain = os.environ.get('SHOPIFY_APP_DOMAIN')
if not _shopify_app_domain and _shopify_app_url:
    _shopify_app_domain = urlparse(_shopify_app_url).hostname

if _shopify_app_domain:
    ALLOWED_HOSTS.append(_shopify_app_domain)
if _shopify_app_url:
    CSRF_TRUSTED_ORIGINS.append(_shopify_app_url)

# Shopify CLI --use-localhost terminates TLS and proxies to Django over HTTP.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'daphne',
    'custom.apps.CustomConfig',

    #'wagtail_localize',
    'wagtail.locales',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.simple_translation',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',

    'wagtail',

    'taggit',
    'modelcluster',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core.apps.CoreConfig',
    'webhooks.apps.WebhooksConfig',
    'shopify_content',
    'api',
    'django_celery_beat',
]

MIDDLEWARE = [
    'core.debug_middleware.ShopifyLocalProxyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

X_FRAME_OPTIONS = 'ALLOWALL' # Allow embedding the app in Shopify

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.shopify_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        },
    }




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-US'

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ('en-US', 'English (United States)'),
    ('es-US', 'Spanish (United States)'),
    ('en-CA', 'English (Canada)'),
    ('fr-CA', 'French (Canada)'),
]

TIME_ZONE = 'America/Toronto'

USE_I18N = True

WAGTAIL_I18N_ENABLED = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NOTEBOOK_ARGUMENTS = [
    '--ip', '0.0.0.0',
    '--port', '8888',
]
IPYTHON_KERNEL_DISPLAY_NAME = 'Django Kernel'


SHOPIFY_API_KEY = os.environ.get('SHOPIFY_API_KEY')
SHOPIFY_API_SECRET = os.environ.get('SHOPIFY_API_SECRET')
SHOPIFY_APP_DOMAIN = _shopify_app_domain
SHOPIFY_APP_URL = _shopify_app_url or None
SHOPIFY_SCOPES = os.environ.get('SHOPIFY_SCOPES') or os.environ.get('SCOPES')
SHOPIFY_ADMIN_API_VERSION = os.environ.get('SHOPIFY_ADMIN_API_VERSION', '2025-04')

WAGTAILADMIN_BASE_URL = os.environ.get('SHOPIFY_APP_URL', 'http://localhost:8000')
WAGTAIL_SITE_NAME = 'Wagtail Shopify'

_mcp_public_base = (SHOPIFY_APP_URL or WAGTAILADMIN_BASE_URL).rstrip('/')
MCP_BASE_URL = f'{_mcp_public_base}/api/v1'
MCP_DEFAULT_API_KEY = os.environ.get('MCP_DEFAULT_API_KEY', '')

# Hostnames allowed for app_home_parent_redirect targets (comma-separated). Always includes
# admin.shopify.com plus SHOPIFY_APP_URL / SHOPIFY_APP_DOMAIN hosts via embedded_redirects.parent_redirect_allowed_hosts.
_parent_redirect_hosts = os.environ.get('SHOPIFY_PARENT_REDIRECT_ALLOWED_HOSTS', '')
SHOPIFY_PARENT_REDIRECT_ALLOWED_HOSTS = [
    h.strip().lower()
    for h in _parent_redirect_hosts.split(',')
    if h.strip()
]

ALLOWED_LOCALE_CODES = {
    'en-US': 'English (United States)',
    'es-US': 'Spanish (United States)',
    'en-CA': 'English (Canada)',
    'fr-CA': 'French (Canada)',
}

# Celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'false').lower() == 'true'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_DEFAULT_QUEUE = os.environ.get('CELERY_TASK_DEFAULT_QUEUE', 'wagtail_shopify')